name: SSH Connect

on:
  workflow_dispatch:
  schedule:
    # 每小时执行一次，从 UTC 的22:00到23:00（北京时间第二天早上6:00到7:00）
    - cron: '0 22-23 * * *'
    # 每小时执行一次，从 UTC 的0:00到18:00（北京时间早上8:00到次日凌晨2:00）
    - cron: '0 0-18 * * *'

jobs:
  connect:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko
          pip install requests

      - name: Run SSH connection script
        env:
          ACCOUNTS: ${{ secrets.ACCOUNTS_JSON }}
        run: python ssh.py
